package com.example.frontend2.presentation.theme

import androidx.compose.ui.graphics.Color

// Dark Theme
val dark_primary = Color(0xFFFFFFFF)
val dark_onPrimary = Color(0xFFA9A9A9)
val dark_primaryContainer = Color(0xFF000000)
val dark_onPrimaryContainer = Color(0xFFFFFFFF)
val dark_inversePrimary = Color(0xFF136CD6)
val dark_secondary = Color(0xFFFFFFFF)
val dark_onSecondary = Color(0xFF000000)
val dark_secondaryContainer = Color(0xFF000000)
val dark_onSecondaryContainer = Color(0xFF000000)
val dark_tertiary = Color(0xFF000000)
val dark_onTertiary = Color(0xFF000000)
val dark_tertiaryContainer = Color(0xFF000000)
val dark_onTertiaryContainer = Color(0xFF000000)
val dark_background = Color(0xFF000000)
val dark_onBackground = Color(0xFF000000)
val dark_surface = Color(0xFF1A1A1A)
val dark_onSurface = Color(0xFF000000)
val dark_surfaceVariant = Color(0xFF000000)
val dark_onSurfaceVariant = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF000000)
val dark_inverseSurface = Color(0xFF000000)
val dark_inverseOnSurface = Color(0xFF000000)
val dark_error = Color(0xFFFF0000)
val dark_onError = Color(0xFF000000)
val dark_errorContainer = Color(0xFF000000)
val dark_onErrorContainer = Color(0xFF000000)
val dark_outline = Color(0xFF000000)
val dark_outlineVariant = Color(0xFF000000)
val dark_scrim = Color(0xFF000000)
val dark_surfaceBright = Color(0xFF000000)
val dark_surfaceContainer = Color(0xFF000000)
val dark_surfaceContainerHigh = Color(0xFF000000)
val dark_surfaceContainerHighest = Color(0xFF000000)
val dark_surfaceContainerLow = Color(0xFF000000)
val dark_surfaceContainerLowest = Color(0xFF000000)
val dark_surfaceDim = Color(0xFF000000)

// Light Theme
val light_primary = Color(0xFF136CD6)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFFFFF)
val light_onPrimaryContainer = Color(0xFF191919)
val light_inversePrimary = Color(0xFF136CD6)
val light_secondary = Color(0xFF000000)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFFFFF)
val light_onSecondaryContainer = Color(0xFFFFFFFF)
val light_tertiary = Color(0xFFFFFFFF)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFFFFF)
val light_onTertiaryContainer = Color(0xFFFFFFFF)
val light_background = Color(0xFFF4F4F4)
val light_onBackground = Color(0xFFFFFFFF)
val light_surface = Color(0xFFFFFFFF)
val light_onSurface = Color(0xFF191919)
val light_surfaceVariant = Color(0xFFFFFFFF)
val light_onSurfaceVariant = Color(0xFFFFFFFF)
val light_surfaceTint = Color(0xFFFFFFFF)
val light_inverseSurface = Color(0xFFFFFFFF)
val light_inverseOnSurface = Color(0xFFFFFFFF)
val light_error = Color(0xFFFF0000)
val light_onError = Color(0xFFFFFFFF)
val light_errorContainer = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFFFFFFFF)
val light_outline = Color(0xFFFFFFFF)
val light_outlineVariant = Color(0xFFFFFFFF)
val light_scrim = Color(0xFFFFFFFF)
val light_surfaceBright = Color(0xFFFFFFFF)
val light_surfaceContainer = Color(0xFFFFFFFF)
val light_surfaceContainerHigh = Color(0xFFFFFFFF)
val light_surfaceContainerHighest = Color(0xFFFFFFFF)
val light_surfaceContainerLow = Color(0xFFFFFFFF)
val light_surfaceContainerLowest = Color(0xFFFFFFFF)
val light_surfaceDim = Color(0xFFFFFFFF)

// Icon Colors
val iconCarColor = Color(0xFFFD6572)
val iconCalendarColor = Color(0xFFF8BF3F)
val iconBrandColor = Color(0xFF3097FA)
val iconModelColor = Color(0xFF70C941)
val iconPaletteColor = Color(0xFFE95EC7)
val iconNumbersColor = Color(0xFF7E57C2)
val iconQrCodeColor = Color(0xFF26A69A)
val iconSettingsColor = Color(0xFFFF9800)
val iconSeatColor = Color(0xFF795548)
val iconBusinessColor = Color(0xFF5C6BC0)
val iconSaveColor = Color(0xFF2196F3)
val iconEventColor = Color(0xFF4CAF50)

val appointmentNotificationColor = Color(0xFFF8BF3F)
val inspectionNotificationColor = Color(0xFFFD6572)